# Generated by Django 4.0.3 on 2022-04-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('task_status', models.CharField(choices=[('Completed', 'complete'), ('Incomplete', 'incomplete'), ('Not yet started', 'not yet started')], max_length=20)),
                ('task_approval', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
