# Generated by Django 4.0.3 on 2022-04-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_childreninfamily_childuser_parentuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childuser',
            old_name='unique_family_name',
            new_name='family_key',
        ),
    ]
