# Generated by Django 4.0.3 on 2022-04-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Incomplete', 'incomplete'), ('Completed', 'complete'), ('Not yet started', 'not yet started')], max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='familygroup',
            field=models.ManyToManyField(to='main_app.familygroup'),
        ),
    ]
