# Generated by Django 4.0.3 on 2022-04-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_task_users_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Completed', 'complete'), ('Not yet started', 'not yet started'), ('Incomplete', 'incomplete')], max_length=20),
        ),
    ]
