# Generated by Django 4.0.3 on 2022-04-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Not yet started', 'not yet started'), ('Completed', 'complete'), ('Incomplete', 'incomplete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiving_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_user', to='main_app.familygroup'),
        ),
    ]
