# Generated by Django 4.0.3 on 2022-04-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_familygroup_alter_task_task_status_task_familygroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='familygroup',
            new_name='family_group',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Incomplete', 'incomplete'), ('Not yet started', 'not yet started'), ('Completed', 'complete')], max_length=20),
        ),
    ]
