# Generated by Django 4.0.3 on 2022-04-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_unique_family_name_childuser_family_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentuser',
            old_name='unique_family_name',
            new_name='family_key',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Incomplete', 'incomplete'), ('Completed', 'complete'), ('Not yet started', 'not yet started')], max_length=20),
        ),
    ]
