# Generated by Django 4.0.3 on 2022-04-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_unique_family_name_parentuser_family_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childuser',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='childuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Incomplete', 'incomplete'), ('Not yet started', 'not yet started'), ('Completed', 'complete')], max_length=20),
        ),
    ]
