# Generated by Django 4.0.3 on 2022-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_familygroup_task_family_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='family_group',
            new_name='familygroups',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Completed', 'complete'), ('Not yet started', 'not yet started'), ('Incomplete', 'incomplete')], max_length=20),
        ),
    ]
